language: node_js
node_js:
- 10
before_deploy:
- export ELASTIC_BEANSTALK_LABEL=git-$(git rev-parse --verify HEAD --short)
- export ELASTIC_BEANSTALK_DESCRIPTION=https://github.com/Pragmatists/absencebot/tree/$(git rev-parse HEAD)
- yarn build
- ./scripts/predeploy.sh
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
  zip_file: absencebot.zip
  region: eu-central-1
  app: absencebot
  env: prod
  bucket_name: elasticbeanstalk-eu-central-1-049249879741
  on:
    repo: Pragmatists/absencebot
    branch: master
