language: node_js
node_js:
- 10
before_deploy:
- export ELASTIC_BEANSTALK_LABEL=git-$(git rev-parse --verify HEAD --short)
- export ELASTIC_BEANSTALK_DESCRIPTION=https://github.com/Pragmatists/absencebot/tree/$(git rev-parse HEAD)
- yarn build
- ./scripts/predeploy.sh
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAQW54FQ26SBYHX24N
  secret_access_key:
    secure: wNtywxX14+8xA3WC+uY6n8fqA4no0wnfPke4xHHA8TR9eMxLZYxarACJb6Cs2JCatjCXlJjJZMtDYQyT/Uf959/bjzPkgQ8LtmLS0CADc2iHtoceOtybP7UBrVfV1A5uGeqKaPB35bynFCtnbYb5byAJgG7mdEVWHbnVHTpCjf86LJn5Yd1+J5RZO5c43aA+EIxIDvU5Ed3g/h0wljeinFIjDrjtRGLqQ+7BGkrdFXxoYmk9arDl35pnqo86cGVmGE6ljafryHjHEcqUjmIgreDnnZ6LL+gsP5k973YnMROxAy2OvMUVFdnZU6OrEZCzI2kx7uJ39sbzUqce/8+Citfda2+FyTb7/XqrV0Lo1bUU4McvDXdnShOL9yC7tehKsz1qXcTzLwlLP0yWfy1ewVE42vskrTpVraej0aIZew4I7LExVw7Cns2SSGXl9EtznX9xY6r+Va/as3tKJ0Sq4j67pJk0lC3lrhDinFFDKACWzHZNltyQzmsmclvaEZsB2f6Vvgf4hHU4grmAKoLBolrFecVkovMBKQxdkiRbIBg6/h5L8Agvb+HKrzDatSB1Ga+mubv7fWJggtgsZ3erhOUYyXBDZEfZ/AVbBR4fvJC1tuMw4iGD5G1DIvfz+HFdGndIA9mU+h+6DWkRmnGns8NlWWHx3GwDm1GeuRPOJXU=
  skip_cleanup: true
  zip_file: absencebot.zip
  region: eu-central-1
  app: absencebot
  env: prod
  bucket_name: elasticbeanstalk-eu-central-1-049249879741
  on:
    repo: Pragmatists/absencebot
    branch: master
