language: node_js
node_js:
- 10
before_deploy:
- export ELASTIC_BEANSTALK_LABEL=git-$(git rev-parse --verify HEAD --short)
- export ELASTIC_BEANSTALK_DESCRIPTION=https://github.com/Pragmatists/absencebot/tree/$(git rev-parse HEAD)
- yarn build
- ./scripts/predeploy.sh
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAQW54FQ266SYBD7MJ
  secret_access_key:
    secure: ETTAlADR6IPkoRyDbQF0Vwv1IXiYLq+0JVTB09SzuILjPmWXt4SueiYNjWmc26js5YAKcUJnCQdyeMGq59wNFQfRC7K/Lu1t+TOSQFu5Gg8fTTlqBUflDs209Yq5xewgn/+yrK2oEMpVB5yQIjpBU3mLKt+2/XBCcYfbKQfqIQr4HM5T6cFQKDcC8GiqCACSqZ/TUdL91BCUSfq80OlCarEe+osEIDN88T/d97bXGItFSoF/ITBx3jzQVAyCMfC9ZCD1YSEu25xBaAxfqPvpEn+QVFGtZ1eTz6T1r0haWccjRCUhMTp9dRJlVbEXHBqUbK7V5nWUItq8vuwtUUTX/RcA+DI7EGik2AqBYh3gF6j0oH7ikGHjQaFwcArM49z0UeEH/C6Mt4/XlnQxMyuLGE7Y24ZlULh4xvYuFGtS6fvwzFX2HBSQue2uTwPxMSuYJmPJIcMkBJzGBFaDP+6lDe0OD5JQ6cFczKWD91iCWHaHfKf0j3NNskr6iLCbH30co/CvYUlgzcR8IyeQb5R7gcl7xR4gbIqNeZQUtdPQnxFE+ZSyEochJf/a/EFtqK5L5UrbQcFPiA4iJIwMIRdNcRmFakdbkdva+MZ2enemjKZoQeghSOcru7IHSoy4e+xUqZe7T0o6Vwmr/P5mN7X3WmzoqoilSPRT5M/YUKa0Rj8=
  skip_cleanup: true
  zip_file: absencebot.zip
  region: eu-central-1
  app: absencebot
  env: prod
  bucket_name: elasticbeanstalk-eu-central-1-049249879741
  on:
    repo: Pragmatists/absencebot
    branch: master
